### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by ninjz** [hhff/spree-ember#60]
When I run:
`ember install spree-ember-storefront`
I get the following issue:

```Future versions of Ember CLI will not support v0.10.26. Please update to Node 0.12 or io.js.
version: 0.2.3
404 Not Found: spree-ember-storefront
Error: 404 Not Found: spree-ember-storefront
    at CachingRegistryClient.<anonymous> (/Users/caL_/Desktop/habitu/frontend/node_modules/ember-cli/node_modules/npm/node_modules/npm-registry-client/lib/request.js:245:14)
    at Request._callback (/Users/caL_/Desktop/habitu/frontend/node_modules/ember-cli/node_modules/npm/node_modules/npm-registry-client/lib/request.js:170:14)
    at Request.self.callback (/Users/caL_/Desktop/habitu/frontend/node_modules/ember-cli/node_modules/npm/node_modules/request/request.js:368:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/Users/caL_/Desktop/habitu/frontend/node_modules/ember-cli/node_modules/npm/node_modules/request/request.js:1219:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/Users/caL_/Desktop/habitu/frontend/node_modules/ember-cli/node_modules/npm/node_modules/request/request.js:1167:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
```

**Comment by hhff** [comment]
Thanks Ninj!  As the repo says on the frontpage, nothing here is on NPM as of yet.  We're racing to finish everything in the next week, so you'll be able to install in then!  If you'd like to install it directly from Git, hit me up on Gitter: https://gitter.im/hhff/spree-ember
