### ISSUE TITLE
[storefront] Taxons Bar seems broken

### ISSUE THREAD

**Issue by hhff** [hhff/spree-ember#77]
Clicking a Taxon on the taxons bar breaks:

```
GET http://localhost:3000/api/ams/products/%5Bobject%20Object%5D?taxon_id=brand%2Fspree 404 (Not Found)
ember.debug.js:23713 Error while processing route: spree.taxons.index Not Found Error: Not Found
    at ember$data$lib$system$adapter$$Adapter.extend.ajaxError (http://localhost:4200/assets/vendor.js:62365:35)
    at superFunction [as _super] (http://localhost:4200/assets/vendor.js:24365:20)
    at ember$data$lib$adapters$rest$adapter$$default.extend.ajaxError (http://localhost:4200/assets/vendor.js:63141:33)
    at apply (http://localhost:4200/assets/vendor.js:28408:18)
    at superWrapper [as ajaxError] (http://localhost:4200/assets/vendor.js:27990:15)
    at hash.error (http://localhost:4200/assets/vendor.js:62440:45)
    at fire (http://localhost:4200/assets/vendor.js:3350:30)
    at Object.self.fireWith [as rejectWith] (http://localhost:4200/assets/vendor.js:3462:7)
    at done (http://localhost:4200/assets/vendor.js:9518:14)
    at XMLHttpRequest.callback (http://localhost:4200/assets/vendor.js:9920:8)
```

**Comment by yurifrl** [comment]
i have also stumbled in this issue.
